Add Desktop version
Kirabo19/Portfolio pull request #6
Opened 2022-05-04 01:15 UTC by Kirabo19

Add HTML, CSS for the desktop version 
Add media media queries for the functionality of all screen resize

2022-05-04 23:55 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @Kirabo19, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good job in implementing the desktop version.
✔️ All linters are passing
✔️ Correct git-flow.

## Required 
- [ ] Kindly make sure to update your readme file according to the project and add the necessary details.
- [ ] Kindly make sure to stick to the design as much as possible (e.g., font, colours, images, tests, margins) as per the Figma.
- [ ] _Check the comments under the review._

Note:- Most of the design is overlapping and it is because of the media query. Use media query for desktop version only and most of your design will fix.

## Optional suggestions
- [ ] Kindly make sure to fix your contact form as it is submitted without any values.
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 23:55 UTC, sja-thedude commented on css/port.css
> +@media (max-width: 470px) {
- [ ] Kindly remove this media query for the mobile version.  Make sure to use media queries for only Desktop breakpoint in the CSS file.

2022-05-04 23:55 UTC, sja-thedude commented on css/port.css
> +
- [ ] Your design is overlapping for the desktop version and the mobile version as you can see below. Kindly make sure to use media queries for the Desktop breakpoint in the CSS file. The value for the `min-width` property should be in the range of `768px` or wider.
Example: `@media screen and (min-width: 1080px) { // please note that it doesn’t have to be exactly 1080px, any value between 768 and 1440 is ok.`

https://user-images.githubusercontent.com/70269507/166839178-8caef090-7984-4247-a4cd-84df1eae3c71.mov

2022-05-04 23:55 UTC, sja-thedude commented on css/port.css
> +@media (max-width: 470px) {
- [ ] Kindly remove this media query for the mobile version. Make sure to use media queries for only Desktop breakpoint in the CSS file.

2022-05-04 23:55 UTC, sja-thedude commented on css/port.css
> +@media (max-width: 470px) {
- [ ] Kindly remove this media query for the mobile version. Make sure to use media queries for only Desktop breakpoint in the CSS file.

2022-05-04 23:55 UTC, sja-thedude commented on css/port.css
> +@media (max-width: 470px) {
- [ ] Kindly remove this media query for the mobile version. Make sure to use media queries for only Desktop breakpoint in the CSS file.

2022-05-04 23:55 UTC, sja-thedude commented on css/port.css
> +  .menu-icon {
- [ ] Kindly make sure you use both Flexbox and Grid in order to layout the elements on the page. You have used flexbox so kindly use grid for both mobile and desktop version.

2022-05-04 23:55 UTC, sja-thedude commented on index.html
> +          </div>
MOBILE VERSION:

- [ ] Kindly follow the same placeholder name as given in the Figma design.
- [ ] Kindly make sure to follow the given Figma design and layout the elements according to it.
- [ ] Kindly make sure to reduce the extra space on the right side of the contact form as per the Figma design.
- [ ] Make sure to correctly place the background image as per the Figma design.
- [ ] Make sure the button is to the left side and not the centre as per the Figma design.
- [ ] Kindly follow the design as much as possible (e.g., font, colours, images, tests, margins) as per the Figma design.
- [ ] Make sure to follow the correct colour for placeholder text as per the Figma design.

- Figma design:
<img width="236" alt="Screenshot 2022-05-05 at 1 41 40 AM" src="https://user-images.githubusercontent.com/70269507/166839774-b9b2b880-8dec-4a75-8005-6e2d1a02fa0d.png">

- Your design:
<img width="382" alt="Screenshot 2022-05-05 at 2 10 44 AM" src="https://user-images.githubusercontent.com/70269507/166839863-4188fe16-e55d-4565-abc3-9a6b7d1d1865.png">

2022-05-04 23:55 UTC, sja-thedude commented on index.html
> +              <button class="btn" type="submit" >Get in Touch</button>
- [ ] Kindly follow the button interactions for hover, pressed, and enable as per the Figma design. 

<img width="646" alt="Screenshot 2022-05-05 at 2 27 23 AM" src="https://user-images.githubusercontent.com/70269507/166841293-aef7eb66-6983-4f11-b2b8-1bc68199d3f1.png">

2022-05-04 23:55 UTC, sja-thedude commented on index.html
> +        </header>
DESKTOP VERSION:

- [ ] Kindly make sure to add space in the header as per the Figma design. The list (Portfolio, About, Contact) is to the right end. Make sure that there is space on the right side.

Figma design:
<img width="612" alt="Screenshot 2022-05-05 at 1 38 15 AM" src="https://user-images.githubusercontent.com/70269507/166841576-dca5b590-b3ff-4ef8-840b-b8e4a288fa24.png">

Your design:
<img width="1547" alt="Screenshot 2022-05-05 at 2 30 32 AM" src="https://user-images.githubusercontent.com/70269507/166841596-f161de7a-3882-48b6-92bd-b2d641e63e1c.png">

2022-05-04 23:55 UTC, sja-thedude commented on index.html
> +                    <ul class="media_ul">
MOBILE VERSION:

- [ ] Kindly reduce the space for the entire mobile version from the right side.
Figma design:
<img width="304" alt="Screenshot 2022-05-05 at 1 40 19 AM" src="https://user-images.githubusercontent.com/70269507/166842142-3e3cdb10-e3d4-43d0-95bd-06b89ee260a7.png">

Your design:
<img width="416" alt="Screenshot 2022-05-05 at 2 35 01 AM" src="https://user-images.githubusercontent.com/70269507/166842157-424c547c-d43c-433e-ad81-482186665260.png">

2022-05-04 23:55 UTC, sja-thedude commented on index.html
> +                  <li class="media_li"><a href="#" target="_blank"><img src="./images/Twitter-icon.svg" alt="Twitter icon"/></a>
MOBILE VERSION:

- [ ] Kindly make sure the languages list is displayed as per the Figma design for the mobile version.
- [ ] Kindly make sure to reduce the spacing on the right side of the languages as per the Figma design as shown in the video.

Your design:


https://user-images.githubusercontent.com/70269507/166842668-dd4971d3-33c1-49ab-b003-bfe41f43da1f.mov



Figma design:
<img width="236" alt="Screenshot 2022-05-05 at 1 41 16 AM" src="https://user-images.githubusercontent.com/70269507/166842420-d694b476-fa54-4952-b811-398970ec8c2b.png">

2022-05-04 23:55 UTC, sja-thedude commented on index.html
> +                    or sign-ups required.
DESKTOP VERSION:

- [ ] Kindly follow the spacing to the right and left of the cards as per the Figma design. As you can see there is more spacing. Make sure to reduce as per the design.
- [ ] Kindly also make sure to follow the spacing in the cards. There should be space in between the image and text.

Figma design:
<img width="404" alt="Screenshot 2022-05-05 at 1 39 10 AM" src="https://user-images.githubusercontent.com/70269507/166842836-b6a43544-4a15-46cb-b3e1-2deb50bf9dbc.png">

Your design:
<img width="1550" alt="Screenshot 2022-05-05 at 2 47 43 AM" src="https://user-images.githubusercontent.com/70269507/166842840-9687d627-afb8-4d4b-b996-39eb1f0b6000.png">

2022-05-07 22:34 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 22:47 UTC, merged